version: '3.9'

services:
  backend-app:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
    container_name: backend-app
    ports:
      - ${API_PORT}:8000
    command: 'uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000'
    env_file:
      - ../.env
    volumes:
      - ../backend/app/:/app/
    networks:
      backend:

networks:
  backend:
    driver: bridge