version: '3.9'

services:

  frontend-app:
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    command: yarn dev
    stdin_open: true
    tty: true
    env_file:
      - ../.env
    volumes:
      - ../frontend/app/:/app/
    networks:
      backend:

networks:
  backend:
    driver: bridge