version: "3.9"

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mpass
      POSTGRES_DB: db
    ports:
      - 5432:5432


networks:
  backend:
    driver: bridge